// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'seller_profile_mp_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SellerProfileMpModel _$SellerProfileMpModelFromJson(
        Map<String, dynamic> json) =>
    SellerProfileMpModel(
      showProfileHint: json['showProfileHint'] as bool?,
      isTwitterActive: json['isTwitterActive'] as bool?,
      twitterId: json['twitterId'] as String?,
      twitterHint: json['twitterHint'] as String?,
      isFacebookActive: json['isFacebookActive'] as bool?,
      facebookId: json['facebookId'] as String?,
      facebookHint: json['facebookHint'] as String?,
      isInstagramActive: json['isInstagramActive'] as bool?,
      instagramId: json['instagramId'] as String?,
      isgoogleplusActive: json['isgoogleplusActive'] as bool?,
      googleplusId: json['googleplusId'] as String?,
      isYoutubeActive: json['isYoutubeActive'] as bool?,
      youtubeId: json['youtubeId'] as String?,
      isVimeoActive: json['isVimeoActive'] as bool?,
      vimeoId: json['vimeoId'] as String?,
      isPinterestActive: json['isPinterestActive'] as bool?,
      pinterestId: json['pinterestId'] as String?,
      contactNumber: json['contactNumber'] as String?,
      contactNumberHint: json['contactNumberHint'] as String?,
      taxvat: json['taxvat'] as String?,
      taxvatHint: json['taxvatHint'] as String?,
      backgroundColor: json['backgroundColor'] as String?,
      backgroundColorHint: json['backgroundColorHint'] as String?,
      shopTitle: json['shopTitle'] as String?,
      shopTitleHint: json['shopTitleHint'] as String?,
      bannerHint: json['bannerHint'] as String?,
      bannerImage: json['bannerImage'] as String?,
      profileImageHint: json['profileImageHint'] as String?,
      profileImage: json['profileImage'] as String?,
      url: json['url'] as String?,
      companyLocalityHint: json['companyLocalityHint'] as String?,
      companyLocality: json['companyLocality'] as String?,
      companyDescriptionHint: json['companyDescriptionHint'] as String?,
      companyDescription: json['companyDescription'] as String?,
      returnPolicyHint: json['returnPolicyHint'] as String?,
      returnPolicy: json['returnPolicy'] as String?,
      shippingPolicyHint: json['shippingPolicyHint'] as String?,
      shippingPolicy: json['shippingPolicy'] as String?,
      privacyPolicy: json['privacyPolicy'] as String?,
      countryHint: json['countryHint'] as String?,
      country: json['country'] as String?,
      countryList: (json['countryList'] as List<dynamic>?)
          ?.map((e) => CountryListMpModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      flagImageUrl: json['flagImageUrl'] as String?,
      metaKeywordHint: json['metaKeywordHint'] as String?,
      metaKeyword: json['metaKeyword'] as String?,
      metaDescriptionHint: json['metaDescriptionHint'] as String?,
      metaDescription: json['metaDescription'] as String?,
      paymentDetailsHint: json['paymentDetailsHint'] as String?,
      paymentDetails: json['paymentDetails'] as String?,
      isColorPickerEnabled: json['isColorPickerEnabled'] as bool?,
      isSellerPolicyEnabled: json['isSellerPolicyEnabled'] as bool?,
      pickUpLatitude: json['pickUpLatitude'] as String?,
      pickUpLongitude: json['pickUpLongitude'] as String?,
      pickUpAddress: json['pickUpAddress'] as String?,
      isMPDeliveryBoyEnabled: json['isMPDeliveryBoyEnabled'] as bool?,
    )
      ..success = json['success'] as bool?
      ..message = json['message'] as String?
      ..otherError = json['otherError'] as String?
      ..redirect = json['redirect'] as String?
      ..eTag = json['eTag'] as String?
      ..cartCount = (json['cartCount'] as num?)?.toInt();

Map<String, dynamic> _$SellerProfileMpModelToJson(
        SellerProfileMpModel instance) =>
    <String, dynamic>{
      'success': instance.success,
      'message': instance.message,
      'otherError': instance.otherError,
      'redirect': instance.redirect,
      'eTag': instance.eTag,
      'cartCount': instance.cartCount,
      'showProfileHint': instance.showProfileHint,
      'isTwitterActive': instance.isTwitterActive,
      'twitterId': instance.twitterId,
      'twitterHint': instance.twitterHint,
      'isFacebookActive': instance.isFacebookActive,
      'facebookId': instance.facebookId,
      'facebookHint': instance.facebookHint,
      'isInstagramActive': instance.isInstagramActive,
      'instagramId': instance.instagramId,
      'isgoogleplusActive': instance.isgoogleplusActive,
      'googleplusId': instance.googleplusId,
      'isYoutubeActive': instance.isYoutubeActive,
      'youtubeId': instance.youtubeId,
      'isVimeoActive': instance.isVimeoActive,
      'vimeoId': instance.vimeoId,
      'isPinterestActive': instance.isPinterestActive,
      'pinterestId': instance.pinterestId,
      'contactNumber': instance.contactNumber,
      'contactNumberHint': instance.contactNumberHint,
      'taxvat': instance.taxvat,
      'taxvatHint': instance.taxvatHint,
      'backgroundColor': instance.backgroundColor,
      'backgroundColorHint': instance.backgroundColorHint,
      'shopTitle': instance.shopTitle,
      'shopTitleHint': instance.shopTitleHint,
      'bannerHint': instance.bannerHint,
      'bannerImage': instance.bannerImage,
      'profileImageHint': instance.profileImageHint,
      'profileImage': instance.profileImage,
      'url': instance.url,
      'companyLocalityHint': instance.companyLocalityHint,
      'companyLocality': instance.companyLocality,
      'companyDescriptionHint': instance.companyDescriptionHint,
      'companyDescription': instance.companyDescription,
      'returnPolicyHint': instance.returnPolicyHint,
      'returnPolicy': instance.returnPolicy,
      'shippingPolicyHint': instance.shippingPolicyHint,
      'shippingPolicy': instance.shippingPolicy,
      'privacyPolicy': instance.privacyPolicy,
      'countryHint': instance.countryHint,
      'country': instance.country,
      'countryList': instance.countryList,
      'flagImageUrl': instance.flagImageUrl,
      'metaKeywordHint': instance.metaKeywordHint,
      'metaKeyword': instance.metaKeyword,
      'metaDescriptionHint': instance.metaDescriptionHint,
      'metaDescription': instance.metaDescription,
      'paymentDetailsHint': instance.paymentDetailsHint,
      'paymentDetails': instance.paymentDetails,
      'isColorPickerEnabled': instance.isColorPickerEnabled,
      'isSellerPolicyEnabled': instance.isSellerPolicyEnabled,
      'pickUpLatitude': instance.pickUpLatitude,
      'pickUpLongitude': instance.pickUpLongitude,
      'pickUpAddress': instance.pickUpAddress,
      'isMPDeliveryBoyEnabled': instance.isMPDeliveryBoyEnabled,
    };
